#!/bin/bash

# This bash script query the ip of domain from 114.114.114.114 and world clear DNS.
# We can tell wether the DNS is polluted From the result. 



# print the seek result
printResult() {
  WHO=$1
  WHAT=$2
  printf "%0.s=" {1..10}
  printf "\n"
  echo "$WHO says: "
  echo " $WHAT"
}


# program usage
usage() {
    echo "Usgae: ./seekDNS [Domain Name]"
}


# retrieve ip of input domain from world and chinese dns
seek() {
    DOMAIN=$1
    ChinaDNS=114.114.114.114
    WorldIP=$(dig $DOMAIN +noall +answer +short)
    ChinaIP=$(dig $DOMAIN @$ChinaDNS +noall +answer +short)

    printResult "World" "$WorldIP"
    printResult "$ChinaDNS" "$ChinaIP"
}


# begin: program entry
if [ "$#" -ne 1 ]; then
    echo "Error: Illegal number of parameters"
    usage
    exit 1
fi

seek $1
# end: program entry 

